## Differ HDF files using h5diff 🔎


#### Imports

In [4]:
import numpy as np
import h5py
import subprocess

#### Creating two similar HDF Files

In [5]:
data = np.random.rand(5, 5)

with h5py.File('file1.h5', 'w') as f1:
    f1.create_dataset('matrix', data=data)

with h5py.File('file2.h5', 'w') as f2:
    f2.create_dataset('matrix', data=data)

with h5py.File('file1.h5', 'r') as f1, h5py.File('file2.h5', 'r') as f2:
    print("Matrix from file1:")
    print(f1['matrix'][:])
    print("\nMatrix from file2:")
    print(f2['matrix'][:])


Matrix from file1:
[[0.57703817 0.94985309 0.29442085 0.48146866 0.24340849]
 [0.04766273 0.10645745 0.03062755 0.28627627 0.93016982]
 [0.77425387 0.91455966 0.93236565 0.22986243 0.68804493]
 [0.75443301 0.43891525 0.29301807 0.08136928 0.76677073]
 [0.01420831 0.39119223 0.97774239 0.54237263 0.65388441]]

Matrix from file2:
[[0.57703817 0.94985309 0.29442085 0.48146866 0.24340849]
 [0.04766273 0.10645745 0.03062755 0.28627627 0.93016982]
 [0.77425387 0.91455966 0.93236565 0.22986243 0.68804493]
 [0.75443301 0.43891525 0.29301807 0.08136928 0.76677073]
 [0.01420831 0.39119223 0.97774239 0.54237263 0.65388441]]


#### Compare files using h5diff

In [7]:
try:
    result = subprocess.run(['h5diff', 'file1.h5', 'file2.h5'])
    print("Files are identical" if result.returncode == 0 else "Files are different")
except Exception as e:
    print(f"Error: {e}")

Files are identical
